// Engine-free migration runner: applies every SQL file under
// prisma/migrations/*/migration.sql (in name order) to the SQLite DB via
// the libsql driver, tracking what has run in the same
// `_prisma_migrations` table Prisma uses.
//
// Why not `prisma migrate dev`? It downloads a schema-engine binary from
// binaries.prisma.sh, which is blocked on many networks (see SETUP.md 2b).
// This script needs nothing beyond `npm install`. `prisma migrate dev`
// still works where the download succeeds — both record into the same
// table, so they can be mixed.
import 'dotenv/config'
import fs from 'fs'
import path from 'path'
import crypto from 'crypto'
import { createClient } from '@libsql/client'
import { resolveDatabaseUrl, serverRoot } from '../src/prisma'

const MIGRATIONS_DIR = path.resolve(serverRoot(), 'prisma', 'migrations')

function splitStatements(sql: string): string[] {
  // Migrations generated by Prisma are simple: no triggers/procedures, so a
  // split on ";" followed by a newline is sufficient.
  return sql
    .split(/;\s*(?:\r?\n|$)/)
    .map(s => s.replace(/^\s*--.*$/gm, '').trim())
    .filter(Boolean)
}

async function main() {
  const url = resolveDatabaseUrl()
  if (url.startsWith('file:')) fs.mkdirSync(path.dirname(url.slice('file:'.length)), { recursive: true })
  const db = createClient({ url })

  await db.execute(`CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
    "id" TEXT PRIMARY KEY NOT NULL,
    "checksum" TEXT NOT NULL,
    "finished_at" DATETIME,
    "migration_name" TEXT NOT NULL,
    "logs" TEXT,
    "rolled_back_at" DATETIME,
    "started_at" DATETIME NOT NULL DEFAULT current_timestamp,
    "applied_steps_count" INTEGER UNSIGNED NOT NULL DEFAULT 0
  )`)

  const applied = new Set(
    (await db.execute('SELECT migration_name FROM "_prisma_migrations" WHERE finished_at IS NOT NULL'))
      .rows.map(r => String(r.migration_name)),
  )

  const dirs = fs.existsSync(MIGRATIONS_DIR)
    ? fs.readdirSync(MIGRATIONS_DIR).filter(d => fs.existsSync(path.join(MIGRATIONS_DIR, d, 'migration.sql'))).sort()
    : []

  let ran = 0
  for (const name of dirs) {
    if (applied.has(name)) continue
    const sql = fs.readFileSync(path.join(MIGRATIONS_DIR, name, 'migration.sql'), 'utf8')
    const checksum = crypto.createHash('sha256').update(sql).digest('hex')
    console.log(`Applying migration ${name}…`)
    const stmts = splitStatements(sql)
    await db.batch(stmts.map(s => ({ sql: s, args: [] })), 'write')
    await db.execute({
      sql: `INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, started_at, applied_steps_count)
            VALUES (?, ?, current_timestamp, ?, NULL, current_timestamp, ?)`,
      args: [crypto.randomUUID(), checksum, name, stmts.length],
    })
    ran++
  }
  console.log(ran ? `Applied ${ran} migration(s) to ${url}` : `Database already up to date (${url})`)
  db.close()
}

main().catch(err => {
  console.error('Migration failed:', err)
  process.exit(1)
})
